// <auto-generated />
using System;
using FakeFacebook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeFacebook.Migrations
{
    [DbContext(typeof(FakeFacebookDbContext))]
    [Migration("20251110071053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FakeFacebook.Models.ChatContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime?>("ContentTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CONTENT_TIME");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<int?>("FileCode")
                        .HasColumnType("int")
                        .HasColumnName("FILE_CODE");

                    b.Property<int?>("GroupChatId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_CHAT_ID");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPDATED_TIME");

                    b.HasKey("Id")
                        .HasName("PK_CHAT_CONTENT");

                    b.ToTable("CHAT_CONTENT");
                });

            modelBuilder.Entity("FakeFacebook.Models.ChatGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<string>("GroupAvartar")
                        .HasColumnType("longtext")
                        .HasColumnName("GROUP_AVARTAR");

                    b.Property<bool>("GroupDouble")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("GROUP_DOUBLE");

                    b.Property<string>("GroupName")
                        .HasColumnType("longtext")
                        .HasColumnName("GROUP_NAME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("PK_CHAT_GROUPS");

                    b.ToTable("CHAT_GROUPS");
                });

            modelBuilder.Entity("FakeFacebook.Models.FeelingPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("Feeling")
                        .HasColumnType("longtext")
                        .HasColumnName("FEELING");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("POST_ID");

                    b.HasKey("Id")
                        .HasName("PK_FEELING_POST");

                    b.ToTable("FEELING_POST");
                });

            modelBuilder.Entity("FakeFacebook.Models.FileChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("DELETED_BY");

                    b.Property<int?>("FileCode")
                        .HasColumnType("int")
                        .HasColumnName("FILE_CODE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("NAME");

                    b.Property<string>("NameExtension")
                        .HasColumnType("longtext")
                        .HasColumnName("NAME_EXTENSION");

                    b.Property<string>("Path")
                        .HasColumnType("longtext")
                        .HasColumnName("PATH");

                    b.Property<string>("ServerCode")
                        .HasColumnType("longtext")
                        .HasColumnName("SERVER_CODE");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("SIZE");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("TYPE");

                    b.HasKey("Id")
                        .HasName("PK_FILE_CHAT");

                    b.ToTable("FILE_CHAT");
                });

            modelBuilder.Entity("FakeFacebook.Models.FileInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int")
                        .HasColumnName("CODE");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("NAME");

                    b.Property<string>("Path")
                        .HasColumnType("longtext")
                        .HasColumnName("PATH");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("TYPE");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPDATED_TIME");

                    b.HasKey("Id")
                        .HasName("PK_FILE_INFORMATION");

                    b.ToTable("FILE_INFORMATION");
                });

            modelBuilder.Entity("FakeFacebook.Models.FriendDouble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("STATUS");

                    b.Property<int>("UserCode1")
                        .HasColumnType("int")
                        .HasColumnName("USER_CODE1");

                    b.Property<int>("UserCode2")
                        .HasColumnType("int")
                        .HasColumnName("USER_CODE2");

                    b.HasKey("Id")
                        .HasName("PK_FRIENDS_DOUBLE");

                    b.ToTable("FRIENDS_DOUBLE");
                });

            modelBuilder.Entity("FakeFacebook.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int")
                        .HasColumnName("DELETED_BY");

                    b.Property<DateTime>("DeletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DELETED_TIME");

                    b.Property<int>("GroupChatId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_CHAT_ID");

                    b.Property<int>("InvitedBy")
                        .HasColumnType("int")
                        .HasColumnName("INVITED_BY");

                    b.Property<DateTime>("InvitedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("INVITED_TIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int?>("MemberCode")
                        .HasColumnType("int")
                        .HasColumnName("MEMBER_CODE");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("PK_GROUP_MEMBER");

                    b.ToTable("GROUP_MEMBER");
                });

            modelBuilder.Entity("FakeFacebook.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("CONTENT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int>("PostCode")
                        .HasColumnType("int")
                        .HasColumnName("POST_CODE");

                    b.HasKey("Id")
                        .HasName("PK_POST_COMMENT");

                    b.ToTable("POST_COMMENT");
                });

            modelBuilder.Entity("FakeFacebook.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentNumber")
                        .HasColumnType("int")
                        .HasColumnName("COMMENT_NUMBER");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("CONTENT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int>("LikeNumber")
                        .HasColumnType("int")
                        .HasColumnName("LIKE_NUMBER");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("PK_POSTS");

                    b.ToTable("POSTS");
                });

            modelBuilder.Entity("FakeFacebook.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool?>("IsEncryption")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ENCRYPTION");

                    b.Property<string>("Permission")
                        .HasColumnType("longtext")
                        .HasColumnName("PERMISSION");

                    b.Property<string>("Provider")
                        .HasColumnType("longtext")
                        .HasColumnName("PROVIDER");

                    b.Property<string>("ProviderSub")
                        .HasColumnType("longtext")
                        .HasColumnName("PROVIDER_SUB");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("ROLE");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPDATED_TIME");

                    b.Property<int>("UserCode")
                        .HasColumnType("int")
                        .HasColumnName("USER_CODE");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("UserPassword")
                        .HasColumnType("longtext")
                        .HasColumnName("USER_PASSWORD");

                    b.HasKey("Id")
                        .HasName("PK_USER_ACCOUNT");

                    b.ToTable("USER_ACCOUNT");
                });

            modelBuilder.Entity("FakeFacebook.Models.UserInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("AVATAR");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BIRTHDAY");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("FileCode")
                        .HasColumnType("int")
                        .HasColumnName("FILE_CODE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool?>("IsEncryption")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ENCRYPTION");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPDATED_TIME");

                    b.HasKey("Id")
                        .HasName("PK_USER_INFORMATION");

                    b.ToTable("USER_INFORMATION");
                });

            modelBuilder.Entity("FakeFacebook.Models.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_TIME");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TOKEN");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_USER_TOKENS");

                    b.ToTable("USER_TOKENS");
                });
#pragma warning restore 612, 618
        }
    }
}
